define(function(require) {
  'use strict';
  var angular = require('angular'),
    emulateButton = require('./emulatebutton'),
    autoFocus = require('./autoFocus'),
    validFile = require('./validFile'),
    autoGrow = require('./autoGrow'),
    uiToggleClass = require('./uiToggleClass'),
    app = require('./app'),
    filePath = require('./filePath'),
    ngMatch = require('./ngMatch'),
    noBreak = require('./noBreak'),
    loadingBar = require('./loadingBar'),
    spinner = require('./spinner'),
    permission = require('./permission'),
    menuPermission = require('./menuPermission'),
    loadingButton = require('./loadingButton'),
    onImageError = require('./onImageError'),
    addTask = require('./addTask/addTask'),
    taskInfo = require('./taskInfo/taskInfo'),
    taskAssignee = require('./taskAssignee/taskAssignee'),
    taskComment = require('./taskComment/taskComment'),
    taskBudget = require('./taskBudget/taskBudget'),
    taskProgress = require('./taskProgress/taskProgress'),
    taskAttachment = require('./taskAttachment/taskAttachment'),
    customScroll = require('./customScroll');

  var module = angular.module('common.directives',
    [
      'common.directives.emulatebutton',
      'common.directives.autoFocus',
      'common.directives.autoGrow',
      'common.directives.validFile',
      'common.directives.uiToggleClass',
      'common.directives.app',
      'common.directives.ngMatch',
      'common.directives.filePath',
      'common.directives.noBreak',
      'common.directives.loadingBar',
      'common.directives.spinner',
      'common.directives.permission',
      'common.directives.menuPermission',
      'common.directives.loadingButton',
      'common.directives.onImageError',
      'common.directives.addTask',
      'common.directives.taskInfo',
      'common.directives.taskAssignee',
      'common.directives.taskComment',
      'common.directives.taskBudget',
      'common.directives.taskProgress',
      'common.directives.taskAttachment',
      'common.directives.customScroll'
    ]);
  return module;
});